-- RetriFlow PostgreSQL legacy migration script
-- Usage:
-- 1. Run this script on an existing/old RetriFlow database.
-- 2. Then run tools/postgres/init_data_pg.sql if you still need seed data.
-- 3. This file is safe to run multiple times.

CREATE EXTENSION IF NOT EXISTS vector;

ALTER TABLE IF EXISTS sessions
    ADD COLUMN IF NOT EXISTS owner_id TEXT NOT NULL DEFAULT '';

CREATE TABLE IF NOT EXISTS users (
    id            TEXT PRIMARY KEY,
    username      TEXT NOT NULL UNIQUE,
    password_hash TEXT NOT NULL,
    role          TEXT NOT NULL DEFAULT 'user',
    created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS knowledge_base_route_profiles (
    knowledge_base_id     TEXT PRIMARY KEY REFERENCES knowledge_bases(id) ON DELETE CASCADE,
    profile_text          TEXT NOT NULL DEFAULT '',
    sample_questions_json JSONB NOT NULL DEFAULT '[]'::jsonb,
    keywords_json         JSONB NOT NULL DEFAULT '[]'::jsonb,
    updated_at            TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE IF EXISTS knowledge_documents
    ADD COLUMN IF NOT EXISTS vector_index_status TEXT NOT NULL DEFAULT 'pending';

ALTER TABLE IF EXISTS knowledge_documents
    ADD COLUMN IF NOT EXISTS vector_chunk_count INTEGER NOT NULL DEFAULT 0;

ALTER TABLE IF EXISTS knowledge_documents
    ADD COLUMN IF NOT EXISTS vector_indexed_at TIMESTAMPTZ;

ALTER TABLE IF EXISTS knowledge_chunks
    ADD COLUMN IF NOT EXISTS strategy TEXT NOT NULL DEFAULT 'recursive';

ALTER TABLE IF EXISTS knowledge_chunks
    ADD COLUMN IF NOT EXISTS document_type TEXT NOT NULL DEFAULT 'manual';

ALTER TABLE IF EXISTS knowledge_chunks
    ADD COLUMN IF NOT EXISTS metadata_json JSONB NOT NULL DEFAULT '{}'::jsonb;

CREATE TABLE IF NOT EXISTS knowledge_document_blocks (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    knowledge_base_id TEXT NOT NULL REFERENCES knowledge_bases(id) ON DELETE CASCADE,
    document_id       BIGINT NOT NULL REFERENCES knowledge_documents(id) ON DELETE CASCADE,
    block_index       INTEGER NOT NULL,
    block_type        TEXT NOT NULL,
    page_number       INTEGER,
    heading_path_json JSONB NOT NULL DEFAULT '[]'::jsonb,
    level             INTEGER,
    text              TEXT,
    headers_json      JSONB NOT NULL DEFAULT '[]'::jsonb,
    row_count         INTEGER,
    column_count      INTEGER,
    caption           TEXT,
    created_at        TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS knowledge_document_table_cells (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    block_id     BIGINT NOT NULL REFERENCES knowledge_document_blocks(id) ON DELETE CASCADE,
    row_index    INTEGER NOT NULL,
    column_index INTEGER NOT NULL,
    text         TEXT NOT NULL DEFAULT '',
    is_header    INTEGER NOT NULL DEFAULT 0,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS conversation_memory_summaries (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id      TEXT NOT NULL REFERENCES sessions(id) ON DELETE CASCADE,
    content         TEXT NOT NULL,
    last_message_id BIGINT NOT NULL,
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    expires_at      TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS conversation_mid_memories (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id  TEXT NOT NULL REFERENCES sessions(id) ON DELETE CASCADE,
    memory_type TEXT NOT NULL DEFAULT 'topic',
    content     TEXT NOT NULL,
    status      TEXT NOT NULL DEFAULT 'active',
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    expires_at  TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS conversation_long_memories (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_type  TEXT NOT NULL DEFAULT 'session',
    owner_id    TEXT NOT NULL,
    memory_type TEXT NOT NULL DEFAULT 'preference',
    content     TEXT NOT NULL,
    status      TEXT NOT NULL DEFAULT 'active',
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    expires_at  TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_knowledge_documents_kb
ON knowledge_documents (knowledge_base_id);

CREATE INDEX IF NOT EXISTS idx_knowledge_chunks_doc
ON knowledge_chunks (document_id, chunk_index);

CREATE INDEX IF NOT EXISTS idx_structured_blocks_doc
ON knowledge_document_blocks (document_id, block_index);

CREATE INDEX IF NOT EXISTS idx_table_cells_block
ON knowledge_document_table_cells (block_id, row_index, column_index);

CREATE INDEX IF NOT EXISTS idx_ingestion_tasks_doc
ON ingestion_tasks (document_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_ingestion_task_nodes_task
ON ingestion_task_nodes (task_id, node_order);

CREATE INDEX IF NOT EXISTS idx_conversation_messages_session
ON conversation_messages (session_id, id);

CREATE INDEX IF NOT EXISTS idx_conversation_memory_summaries_session
ON conversation_memory_summaries (session_id, id DESC);

CREATE INDEX IF NOT EXISTS idx_conversation_mid_memories_session
ON conversation_mid_memories (session_id, id DESC);

CREATE INDEX IF NOT EXISTS idx_conversation_long_memories_owner
ON conversation_long_memories (owner_type, owner_id, id DESC);
