-- RetriFlow PostgreSQL schema
-- Reference style: ragent/resources/database/schema_pg.sql
--
-- Usage:
-- 1. Connect to the target PostgreSQL database.
-- 2. Execute this script to initialize the business schema.
-- 3. The vector table is created lazily by the backend on the first
--    successful embedding write. This keeps the script compatible with
--    clients like HeidiSQL that do not reliably execute DO $$ blocks.

CREATE EXTENSION IF NOT EXISTS vector;

-- ============================================
-- Session & Conversation Tables
-- ============================================

CREATE TABLE IF NOT EXISTS sessions (
    id            TEXT PRIMARY KEY,
    title         TEXT NOT NULL,
    message_count INTEGER NOT NULL DEFAULT 0
);
COMMENT ON TABLE sessions IS 'RetriFlow 会话表';
COMMENT ON COLUMN sessions.id IS '会话 ID';
COMMENT ON COLUMN sessions.title IS '会话标题';
COMMENT ON COLUMN sessions.message_count IS '消息数量';

CREATE TABLE IF NOT EXISTS conversation_messages (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id TEXT NOT NULL REFERENCES sessions(id) ON DELETE CASCADE,
    role       TEXT NOT NULL,
    content    TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_conversation_messages_session
ON conversation_messages (session_id, id);
COMMENT ON TABLE conversation_messages IS 'RetriFlow 会话消息表';
COMMENT ON COLUMN conversation_messages.id IS '消息主键';
COMMENT ON COLUMN conversation_messages.session_id IS '所属会话 ID';
COMMENT ON COLUMN conversation_messages.role IS '消息角色，user/assistant';
COMMENT ON COLUMN conversation_messages.content IS '消息内容';
COMMENT ON COLUMN conversation_messages.created_at IS '创建时间';

-- ============================================
-- Knowledge Base Tables
-- ============================================

CREATE TABLE IF NOT EXISTS knowledge_bases (
    id             TEXT PRIMARY KEY,
    name           TEXT NOT NULL,
    product        TEXT NOT NULL,
    document_count INTEGER NOT NULL DEFAULT 0
);
COMMENT ON TABLE knowledge_bases IS 'RetriFlow 知识库表';
COMMENT ON COLUMN knowledge_bases.id IS '知识库 ID';
COMMENT ON COLUMN knowledge_bases.name IS '知识库名称';
COMMENT ON COLUMN knowledge_bases.product IS '所属产品';
COMMENT ON COLUMN knowledge_bases.document_count IS '文档数量';

CREATE TABLE IF NOT EXISTS knowledge_documents (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    knowledge_base_id TEXT NOT NULL REFERENCES knowledge_bases(id) ON DELETE CASCADE,
    title             TEXT NOT NULL,
    source_type       TEXT NOT NULL,
    content           TEXT NOT NULL,
    status            TEXT NOT NULL DEFAULT 'indexed',
    created_at        TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_knowledge_documents_kb
ON knowledge_documents (knowledge_base_id);
COMMENT ON TABLE knowledge_documents IS 'RetriFlow 知识库文档表';
COMMENT ON COLUMN knowledge_documents.id IS '文档 ID';
COMMENT ON COLUMN knowledge_documents.knowledge_base_id IS '所属知识库 ID';
COMMENT ON COLUMN knowledge_documents.title IS '文档标题';
COMMENT ON COLUMN knowledge_documents.source_type IS '来源类型';
COMMENT ON COLUMN knowledge_documents.content IS '归一化后的全文内容';
COMMENT ON COLUMN knowledge_documents.status IS '文档状态';
COMMENT ON COLUMN knowledge_documents.created_at IS '创建时间';

CREATE TABLE IF NOT EXISTS knowledge_chunks (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    knowledge_base_id TEXT NOT NULL REFERENCES knowledge_bases(id) ON DELETE CASCADE,
    document_id       BIGINT NOT NULL REFERENCES knowledge_documents(id) ON DELETE CASCADE,
    chunk_index       INTEGER NOT NULL,
    content           TEXT NOT NULL,
    char_count        INTEGER NOT NULL,
    strategy          TEXT NOT NULL DEFAULT 'recursive',
    document_type     TEXT NOT NULL DEFAULT 'manual',
    metadata_json     JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at        TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_knowledge_chunks_doc
ON knowledge_chunks (document_id, chunk_index);
COMMENT ON TABLE knowledge_chunks IS 'RetriFlow 文档分块表';
COMMENT ON COLUMN knowledge_chunks.id IS '分块 ID';
COMMENT ON COLUMN knowledge_chunks.knowledge_base_id IS '所属知识库 ID';
COMMENT ON COLUMN knowledge_chunks.document_id IS '所属文档 ID';
COMMENT ON COLUMN knowledge_chunks.chunk_index IS '分块顺序';
COMMENT ON COLUMN knowledge_chunks.content IS '分块内容';
COMMENT ON COLUMN knowledge_chunks.char_count IS '字符数';
COMMENT ON COLUMN knowledge_chunks.strategy IS '分块策略';
COMMENT ON COLUMN knowledge_chunks.document_type IS '文档类型';
COMMENT ON COLUMN knowledge_chunks.metadata_json IS '分块元数据';
COMMENT ON COLUMN knowledge_chunks.created_at IS '创建时间';

-- ============================================
-- Structured Document Tables
-- ============================================

CREATE TABLE IF NOT EXISTS knowledge_document_blocks (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    knowledge_base_id TEXT NOT NULL REFERENCES knowledge_bases(id) ON DELETE CASCADE,
    document_id       BIGINT NOT NULL REFERENCES knowledge_documents(id) ON DELETE CASCADE,
    block_index       INTEGER NOT NULL,
    block_type        TEXT NOT NULL,
    page_number       INTEGER,
    heading_path_json JSONB NOT NULL DEFAULT '[]'::jsonb,
    level             INTEGER,
    text              TEXT,
    headers_json      JSONB NOT NULL DEFAULT '[]'::jsonb,
    row_count         INTEGER,
    column_count      INTEGER,
    caption           TEXT,
    created_at        TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_structured_blocks_doc
ON knowledge_document_blocks (document_id, block_index);
COMMENT ON TABLE knowledge_document_blocks IS 'RetriFlow 结构化文档块表';
COMMENT ON COLUMN knowledge_document_blocks.id IS '结构化块 ID';
COMMENT ON COLUMN knowledge_document_blocks.knowledge_base_id IS '所属知识库 ID';
COMMENT ON COLUMN knowledge_document_blocks.document_id IS '所属文档 ID';
COMMENT ON COLUMN knowledge_document_blocks.block_index IS '块顺序';
COMMENT ON COLUMN knowledge_document_blocks.block_type IS '块类型，heading/paragraph/table/image_caption/page_break';
COMMENT ON COLUMN knowledge_document_blocks.page_number IS '页码';
COMMENT ON COLUMN knowledge_document_blocks.heading_path_json IS '标题层级路径';
COMMENT ON COLUMN knowledge_document_blocks.level IS '标题级别';
COMMENT ON COLUMN knowledge_document_blocks.text IS '块文本';
COMMENT ON COLUMN knowledge_document_blocks.headers_json IS '表头数组';
COMMENT ON COLUMN knowledge_document_blocks.row_count IS '表格行数';
COMMENT ON COLUMN knowledge_document_blocks.column_count IS '表格列数';
COMMENT ON COLUMN knowledge_document_blocks.caption IS '图片或表格说明';
COMMENT ON COLUMN knowledge_document_blocks.created_at IS '创建时间';

CREATE TABLE IF NOT EXISTS knowledge_document_table_cells (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    block_id     BIGINT NOT NULL REFERENCES knowledge_document_blocks(id) ON DELETE CASCADE,
    row_index    INTEGER NOT NULL,
    column_index INTEGER NOT NULL,
    text         TEXT NOT NULL DEFAULT '',
    is_header    INTEGER NOT NULL DEFAULT 0,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_table_cells_block
ON knowledge_document_table_cells (block_id, row_index, column_index);
COMMENT ON TABLE knowledge_document_table_cells IS 'RetriFlow 结构化表格单元格表';
COMMENT ON COLUMN knowledge_document_table_cells.id IS '单元格 ID';
COMMENT ON COLUMN knowledge_document_table_cells.block_id IS '所属表格块 ID';
COMMENT ON COLUMN knowledge_document_table_cells.row_index IS '行号';
COMMENT ON COLUMN knowledge_document_table_cells.column_index IS '列号';
COMMENT ON COLUMN knowledge_document_table_cells.text IS '单元格文本';
COMMENT ON COLUMN knowledge_document_table_cells.is_header IS '是否表头';
COMMENT ON COLUMN knowledge_document_table_cells.created_at IS '创建时间';

-- ============================================
-- Ingestion Tables
-- ============================================

CREATE TABLE IF NOT EXISTS ingestion_tasks (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    knowledge_base_id TEXT NOT NULL REFERENCES knowledge_bases(id) ON DELETE CASCADE,
    document_id       BIGINT NOT NULL REFERENCES knowledge_documents(id) ON DELETE CASCADE,
    source_type       TEXT NOT NULL,
    status            TEXT NOT NULL,
    chunk_count       INTEGER NOT NULL DEFAULT 0,
    message           TEXT NOT NULL DEFAULT '',
    created_at        TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_ingestion_tasks_doc
ON ingestion_tasks (document_id, created_at DESC);
COMMENT ON TABLE ingestion_tasks IS 'RetriFlow 入库任务表';
COMMENT ON COLUMN ingestion_tasks.id IS '任务 ID';
COMMENT ON COLUMN ingestion_tasks.knowledge_base_id IS '所属知识库 ID';
COMMENT ON COLUMN ingestion_tasks.document_id IS '所属文档 ID';
COMMENT ON COLUMN ingestion_tasks.source_type IS '来源类型';
COMMENT ON COLUMN ingestion_tasks.status IS '任务状态';
COMMENT ON COLUMN ingestion_tasks.chunk_count IS '生成的 chunk 数量';
COMMENT ON COLUMN ingestion_tasks.message IS '任务说明';
COMMENT ON COLUMN ingestion_tasks.created_at IS '创建时间';

CREATE TABLE IF NOT EXISTS ingestion_task_nodes (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id     BIGINT NOT NULL REFERENCES ingestion_tasks(id) ON DELETE CASCADE,
    node_type   TEXT NOT NULL,
    node_order  INTEGER NOT NULL,
    success     INTEGER NOT NULL,
    message     TEXT NOT NULL DEFAULT '',
    duration_ms INTEGER NOT NULL DEFAULT 0,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_ingestion_task_nodes_task
ON ingestion_task_nodes (task_id, node_order);
COMMENT ON TABLE ingestion_task_nodes IS 'RetriFlow 入库任务节点表';
COMMENT ON COLUMN ingestion_task_nodes.id IS '节点记录 ID';
COMMENT ON COLUMN ingestion_task_nodes.task_id IS '所属任务 ID';
COMMENT ON COLUMN ingestion_task_nodes.node_type IS '节点类型';
COMMENT ON COLUMN ingestion_task_nodes.node_order IS '节点顺序';
COMMENT ON COLUMN ingestion_task_nodes.success IS '是否成功';
COMMENT ON COLUMN ingestion_task_nodes.message IS '节点说明';
COMMENT ON COLUMN ingestion_task_nodes.duration_ms IS '耗时毫秒';
COMMENT ON COLUMN ingestion_task_nodes.created_at IS '创建时间';

-- ============================================
-- Vector Table Note
-- ============================================

-- retriflow_chunk_vectors is created automatically by the backend when the
-- first embedding write succeeds. The concrete vector dimension is inferred
-- from the active embedding model at runtime.
