-- RetriFlow PostgreSQL schema
-- Usage:
-- 1. Connect to the target PostgreSQL database.
-- 2. Execute this script to initialize the business schema.
-- 3. The vector table is created lazily by the backend on the first
--    successful embedding write, so this file stays compatible with GUI clients.

CREATE EXTENSION IF NOT EXISTS vector;

-- ============================================
-- Session & User Tables
-- ============================================

CREATE TABLE IF NOT EXISTS sessions (
    id            TEXT PRIMARY KEY,
    title         TEXT NOT NULL,
    message_count INTEGER NOT NULL DEFAULT 0,
    owner_id      TEXT NOT NULL DEFAULT ''
);

CREATE TABLE IF NOT EXISTS users (
    id            TEXT PRIMARY KEY,
    username      TEXT NOT NULL UNIQUE,
    password_hash TEXT NOT NULL,
    role          TEXT NOT NULL DEFAULT 'user',
    avatar_url    TEXT NOT NULL DEFAULT '',
    created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
ALTER TABLE users
ADD COLUMN IF NOT EXISTS avatar_url TEXT NOT NULL DEFAULT '';

CREATE TABLE IF NOT EXISTS conversation_messages (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id TEXT NOT NULL REFERENCES sessions(id) ON DELETE CASCADE,
    role       TEXT NOT NULL,
    content    TEXT NOT NULL,
    duration_ms INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_conversation_messages_session
ON conversation_messages (session_id, id);
ALTER TABLE conversation_messages
ADD COLUMN IF NOT EXISTS duration_ms INTEGER NOT NULL DEFAULT 0;

CREATE TABLE IF NOT EXISTS message_feedback (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    message_id BIGINT NOT NULL REFERENCES conversation_messages(id) ON DELETE CASCADE,
    session_id TEXT NOT NULL REFERENCES sessions(id) ON DELETE CASCADE,
    user_id    TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    vote       INTEGER NOT NULL,
    reason     TEXT NOT NULL DEFAULT '',
    comment    TEXT NOT NULL DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE UNIQUE INDEX IF NOT EXISTS idx_message_feedback_user_message
ON message_feedback (message_id, user_id);

CREATE TABLE IF NOT EXISTS rag_trace_nodes (
    id             TEXT PRIMARY KEY,
    session_id     TEXT NOT NULL,
    task_id        TEXT NOT NULL DEFAULT '',
    parent_id      TEXT NOT NULL DEFAULT '',
    name           TEXT NOT NULL,
    node_type      TEXT NOT NULL DEFAULT 'METHOD',
    status         TEXT NOT NULL DEFAULT 'running',
    input_summary  TEXT NOT NULL DEFAULT '',
    output_summary TEXT NOT NULL DEFAULT '',
    error_message  TEXT NOT NULL DEFAULT '',
    metadata_json  JSONB NOT NULL DEFAULT '{}'::jsonb,
    started_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    finished_at    TIMESTAMPTZ,
    duration_ms    INTEGER NOT NULL DEFAULT 0
);
CREATE INDEX IF NOT EXISTS idx_rag_trace_nodes_session
ON rag_trace_nodes (session_id, started_at);
CREATE INDEX IF NOT EXISTS idx_rag_trace_nodes_parent
ON rag_trace_nodes (parent_id);

-- ============================================
-- Knowledge Base Tables
-- ============================================

CREATE TABLE IF NOT EXISTS knowledge_bases (
    id              TEXT PRIMARY KEY,
    name            TEXT NOT NULL,
    product         TEXT NOT NULL,
    document_count  INTEGER NOT NULL DEFAULT 0,
    embedding_model TEXT NOT NULL DEFAULT 'Qwen/Qwen3-Embedding-8B',
    collection_name TEXT NOT NULL DEFAULT '',
    owner           TEXT NOT NULL DEFAULT 'admin',
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
ALTER TABLE knowledge_bases
ADD COLUMN IF NOT EXISTS embedding_model TEXT NOT NULL DEFAULT 'Qwen/Qwen3-Embedding-8B';
ALTER TABLE knowledge_bases
ADD COLUMN IF NOT EXISTS collection_name TEXT NOT NULL DEFAULT '';
ALTER TABLE knowledge_bases
ADD COLUMN IF NOT EXISTS owner TEXT NOT NULL DEFAULT 'admin';
ALTER TABLE knowledge_bases
ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ NOT NULL DEFAULT NOW();
ALTER TABLE knowledge_bases
ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW();

CREATE TABLE IF NOT EXISTS knowledge_base_route_profiles (
    knowledge_base_id     TEXT PRIMARY KEY REFERENCES knowledge_bases(id) ON DELETE CASCADE,
    profile_text          TEXT NOT NULL DEFAULT '',
    sample_questions_json JSONB NOT NULL DEFAULT '[]'::jsonb,
    keywords_json         JSONB NOT NULL DEFAULT '[]'::jsonb,
    updated_at            TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS knowledge_documents (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    knowledge_base_id   TEXT NOT NULL REFERENCES knowledge_bases(id) ON DELETE CASCADE,
    title               TEXT NOT NULL,
    source_type         TEXT NOT NULL,
    source_uri          TEXT NOT NULL DEFAULT '',
    content             TEXT NOT NULL,
    status              TEXT NOT NULL DEFAULT 'indexed',
    vector_index_status TEXT NOT NULL DEFAULT 'pending',
    vector_chunk_count  INTEGER NOT NULL DEFAULT 0,
    vector_indexed_at   TIMESTAMPTZ,
    processing_config_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_knowledge_documents_kb
ON knowledge_documents (knowledge_base_id);

CREATE TABLE IF NOT EXISTS knowledge_chunks (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    knowledge_base_id TEXT NOT NULL REFERENCES knowledge_bases(id) ON DELETE CASCADE,
    document_id       BIGINT NOT NULL REFERENCES knowledge_documents(id) ON DELETE CASCADE,
    chunk_index       INTEGER NOT NULL,
    content           TEXT NOT NULL,
    char_count        INTEGER NOT NULL,
    enabled           INTEGER NOT NULL DEFAULT 1,
    strategy          TEXT NOT NULL DEFAULT 'recursive',
    document_type     TEXT NOT NULL DEFAULT 'manual',
    metadata_json     JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at        TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_knowledge_chunks_doc
ON knowledge_chunks (document_id, chunk_index);
ALTER TABLE knowledge_chunks
ADD COLUMN IF NOT EXISTS enabled INTEGER NOT NULL DEFAULT 1;

-- ============================================
-- Structured Document Tables
-- ============================================

CREATE TABLE IF NOT EXISTS knowledge_document_blocks (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    knowledge_base_id TEXT NOT NULL REFERENCES knowledge_bases(id) ON DELETE CASCADE,
    document_id       BIGINT NOT NULL REFERENCES knowledge_documents(id) ON DELETE CASCADE,
    block_index       INTEGER NOT NULL,
    block_type        TEXT NOT NULL,
    page_number       INTEGER,
    heading_path_json JSONB NOT NULL DEFAULT '[]'::jsonb,
    level             INTEGER,
    text              TEXT,
    headers_json      JSONB NOT NULL DEFAULT '[]'::jsonb,
    row_count         INTEGER,
    column_count      INTEGER,
    caption           TEXT,
    created_at        TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_structured_blocks_doc
ON knowledge_document_blocks (document_id, block_index);

CREATE TABLE IF NOT EXISTS knowledge_document_table_cells (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    block_id     BIGINT NOT NULL REFERENCES knowledge_document_blocks(id) ON DELETE CASCADE,
    row_index    INTEGER NOT NULL,
    column_index INTEGER NOT NULL,
    text         TEXT NOT NULL DEFAULT '',
    is_header    INTEGER NOT NULL DEFAULT 0,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_table_cells_block
ON knowledge_document_table_cells (block_id, row_index, column_index);

-- ============================================
-- Ingestion Tables
-- ============================================

CREATE TABLE IF NOT EXISTS ingestion_tasks (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    knowledge_base_id TEXT NOT NULL REFERENCES knowledge_bases(id) ON DELETE CASCADE,
    document_id       BIGINT NOT NULL REFERENCES knowledge_documents(id) ON DELETE CASCADE,
    source_type       TEXT NOT NULL,
    status            TEXT NOT NULL,
    chunk_count       INTEGER NOT NULL DEFAULT 0,
    message           TEXT NOT NULL DEFAULT '',
    created_at        TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_ingestion_tasks_doc
ON ingestion_tasks (document_id, created_at DESC);

CREATE TABLE IF NOT EXISTS ingestion_pipelines (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        TEXT NOT NULL,
    description TEXT NOT NULL DEFAULT '',
    nodes_json  JSONB NOT NULL DEFAULT '[]'::jsonb,
    owner       TEXT NOT NULL DEFAULT 'admin',
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS ingestion_task_nodes (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id     BIGINT NOT NULL REFERENCES ingestion_tasks(id) ON DELETE CASCADE,
    node_id     TEXT NOT NULL DEFAULT '',
    node_type   TEXT NOT NULL,
    node_order  INTEGER NOT NULL,
    success     INTEGER NOT NULL,
    status      TEXT NOT NULL DEFAULT 'success',
    message     TEXT NOT NULL DEFAULT '',
    error_message TEXT NOT NULL DEFAULT '',
    output_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    duration_ms INTEGER NOT NULL DEFAULT 0,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_ingestion_task_nodes_task
ON ingestion_task_nodes (task_id, node_order);
ALTER TABLE ingestion_task_nodes
ADD COLUMN IF NOT EXISTS node_id TEXT NOT NULL DEFAULT '';
ALTER TABLE ingestion_task_nodes
ADD COLUMN IF NOT EXISTS status TEXT NOT NULL DEFAULT 'success';
ALTER TABLE ingestion_task_nodes
ADD COLUMN IF NOT EXISTS error_message TEXT NOT NULL DEFAULT '';
ALTER TABLE ingestion_task_nodes
ADD COLUMN IF NOT EXISTS output_json JSONB NOT NULL DEFAULT '{}'::jsonb;

-- ============================================
-- Admin Console Tables
-- ============================================

CREATE TABLE IF NOT EXISTS admin_intent_nodes (
    id                    TEXT PRIMARY KEY,
    name                  TEXT NOT NULL,
    code                  TEXT NOT NULL UNIQUE,
    level                 TEXT NOT NULL DEFAULT 'INTENT',
    node_type             TEXT NOT NULL DEFAULT 'KB',
    parent_id             TEXT NOT NULL DEFAULT 'ROOT',
    knowledge_base_id     TEXT NOT NULL DEFAULT '',
    collection_name       TEXT NOT NULL DEFAULT '',
    description           TEXT NOT NULL DEFAULT '',
    sample_questions_json JSONB NOT NULL DEFAULT '[]'::jsonb,
    rule_snippet          TEXT NOT NULL DEFAULT '',
    prompt_template       TEXT NOT NULL DEFAULT '',
    top_k                 INTEGER,
    sort_order            INTEGER NOT NULL DEFAULT 0,
    enabled               INTEGER NOT NULL DEFAULT 1,
    created_at            TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at            TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_admin_intent_nodes_parent
ON admin_intent_nodes (parent_id, sort_order);

CREATE TABLE IF NOT EXISTS admin_keyword_mappings (
    id                TEXT PRIMARY KEY,
    raw_keyword       TEXT NOT NULL,
    target_keyword    TEXT NOT NULL,
    match_type        TEXT NOT NULL DEFAULT 'exact',
    priority          INTEGER NOT NULL DEFAULT 0,
    enabled           INTEGER NOT NULL DEFAULT 1,
    remark            TEXT NOT NULL DEFAULT '',
    knowledge_base_id TEXT NOT NULL DEFAULT '',
    created_at        TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at        TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_admin_keyword_mappings_keyword
ON admin_keyword_mappings (raw_keyword, enabled);

CREATE TABLE IF NOT EXISTS model_health (
    capability               TEXT NOT NULL,
    provider_name            TEXT NOT NULL,
    model                    TEXT NOT NULL,
    state                    TEXT NOT NULL DEFAULT 'healthy',
    failure_count            INTEGER NOT NULL DEFAULT 0,
    success_count            INTEGER NOT NULL DEFAULT 0,
    opened_at                DOUBLE PRECISION,
    last_success_at          DOUBLE PRECISION,
    last_failure_at          DOUBLE PRECISION,
    last_error               TEXT NOT NULL DEFAULT '',
    last_success_duration_ms INTEGER,
    last_first_packet_ms     INTEGER,
    half_open_in_flight      INTEGER NOT NULL DEFAULT 0,
    updated_at               TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (capability, provider_name, model)
);
ALTER TABLE model_health
ADD COLUMN IF NOT EXISTS half_open_in_flight INTEGER NOT NULL DEFAULT 0;
CREATE INDEX IF NOT EXISTS idx_model_health_state
ON model_health (state, provider_name);

-- ============================================
-- Conversation Memory Tables
-- ============================================

CREATE TABLE IF NOT EXISTS conversation_memory_summaries (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id      TEXT NOT NULL REFERENCES sessions(id) ON DELETE CASCADE,
    content         TEXT NOT NULL,
    last_message_id BIGINT NOT NULL,
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    expires_at      TIMESTAMPTZ
);
CREATE INDEX IF NOT EXISTS idx_conversation_memory_summaries_session
ON conversation_memory_summaries (session_id, id DESC);

CREATE TABLE IF NOT EXISTS conversation_mid_memories (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id  TEXT NOT NULL REFERENCES sessions(id) ON DELETE CASCADE,
    memory_type TEXT NOT NULL DEFAULT 'topic',
    content     TEXT NOT NULL,
    status      TEXT NOT NULL DEFAULT 'active',
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    expires_at  TIMESTAMPTZ
);
CREATE INDEX IF NOT EXISTS idx_conversation_mid_memories_session
ON conversation_mid_memories (session_id, id DESC);

CREATE TABLE IF NOT EXISTS conversation_long_memories (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_type  TEXT NOT NULL DEFAULT 'session',
    owner_id    TEXT NOT NULL,
    memory_type TEXT NOT NULL DEFAULT 'preference',
    content     TEXT NOT NULL,
    status      TEXT NOT NULL DEFAULT 'active',
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    expires_at  TIMESTAMPTZ
);
CREATE INDEX IF NOT EXISTS idx_conversation_long_memories_owner
ON conversation_long_memories (owner_type, owner_id, id DESC);

-- ============================================
-- Vector Table Note
-- ============================================

-- retriflow_chunk_vectors is created automatically by the backend when the
-- first embedding write succeeds. The concrete vector dimension is inferred
-- from the active embedding model at runtime.

